[workspace]
resolver = "3"
members = [
    "crates/aa-cli",
    "crates/aa-framework",
    "crates/aa-kernel",
    "crates/client-evm",
    "crates/optimization",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
