[package]
name = "optimization"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
burn = { version = "0.19.0", features = ["wgpu", "ndarray", "train"] }
thiserror = "2.0.17"

[dev-dependencies]
proptest = "1.7"

[lints]
workspace = true
